version: "3.7"
services:
  mongo:
    image: mongo:4.4.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: "SpoonTastic-local"
