AWSTemplateFormatVersion: "2010-09-09"
Description: SpoonTastic
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    BinaryMediaTypes:
      - "*~1*"
Parameters:
  AppImageUri:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - "production"
      - "staging"
      - "development"
  EncryptionKey:
    Type: String
    NoEcho: true
  ReleaseVersion:
    Type: String
  MongoConnectionString:
    Type: String
Conditions:
  IsProduction: !Equals [!Ref Environment, "production"]
  IsStaging: !Equals [!Ref Environment, "staging"]
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: !Ref AppImageUri
      PackageType: Image
      MemorySize: 1024
      Timeout: 30
      Events:
        RootTrigger:
          Type: "Api"
          Properties:
            Path: "/"
            Method: "ANY"
        ProxyTrigger:
          Type: "Api"
          Properties:
            Path: "/{proxy+}"
            Method: "ANY"
      Environment:
        Variables:
          ENCRYPTION_KEY: !Ref EncryptionKey
          NODE_ENV: "production"
          NODE_CONFIG_ENV: !If [IsProduction, "production", "staging"]
          RELEASE_VERSION: !Ref ReleaseVersion
          MONGO_CONNECTION_STRING: !Ref MongoConnectionString
